# just in internet hosting
services:
  db_auth:
    image: postgres:latest                     # Use the latest official PostgreSQL image
    container_name: db_auth                   # Set a custom name for the container
    ports:
      - "5434:5432"                            # Map container port 5433 to host port 5432

    volumes:
      - db_data_1:/var/lib/postgresql/data     # Persist database data between container restarts
    environment:
      POSTGRES_USER: nexoc                     # Username for the PostgreSQL database
      POSTGRES_PASSWORD: ´0880´                  # Password for the database user
      POSTGRES_DB: db_auth                     # Name of the database to create on container startup

  auth_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    ports:
      - "8001:8001"
    depends_on:
      - db_auth
volumes:
  db_data_1: